#!/usr/bin/env bash
# Regenerate the CLI reference (docs/cli-reference.md) from the Typer app.
#
# The command tree — every group, command, option, and its help text — IS the
# source of truth. This walks it and renders Markdown, so a new command is
# documented the moment it has a docstring + help= (see CONTRIBUTING.md).
#
# NEVER hand-edit docs/cli-reference.md; edit the command's docstring / Option
# help= instead, then re-run this. CI fails if the committed file is stale.
#
# Usage:  ./scripts/gen-docs.sh          (run inside the project venv)
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/docs/cli-reference.md"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# typer's `utils docs` introspects the tree without executing the root callback,
# so this never touches the network or needs a PARAMIFY_API_KEY.
typer pfy.app.cli.main utils docs --name pfy --output "$tmp"

{
  printf '<!-- GENERATED by scripts/gen-docs.sh from the Typer app. Do not edit by hand. -->\n\n'
  # Unescape apostrophes so the raw Markdown reads cleanly on GitHub too.
  sed 's/&#x27;/'\''/g' "$tmp"
} >"$out"

echo "wrote $out"
